# Generated by Django 4.2 on 2023-07-31 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinterestmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(upload_to='pins/'),
        ),
    ]
