# Generated by Django 4.2 on 2023-08-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinterestmain', '0007_alter_pin_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideapin',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideapins', to='pinterestmain.board'),
        ),
        migrations.AlterField(
            model_name='ideapin',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideapins', to='pinterestmain.group'),
        ),
    ]
