# Generated by Django 4.2 on 2023-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterestmain', '0008_alter_ideapin_board_alter_ideapin_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boards/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/'),
        ),
        migrations.AlterField(
            model_name='ideapin',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
