# Generated by Django 4.2 on 2023-07-31 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(blank=True, upload_to='hesaplar/')),
                ('isim', models.CharField(blank=True, max_length=100, null=True)),
                ('soyisim', models.CharField(blank=True, max_length=100, null=True)),
                ('hakkinda', models.TextField(blank=True, max_length=500, null=True)),
                ('websitesi', models.URLField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
